services:
  nginx:
    image: nginx:1.21.6
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./project/nginx/config.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    depends_on:
      - webdjango
    networks:
      - djangonetwork 
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=noboringdate
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=asqw12ASQW!@
    ports:
      - "5432:5432"
    networks:
      - djangonetwork
  webdjango:
    build: .
    container_name: django
    #  command: python manage.py runserver 0.0.0.0:8000
    entrypoint: ["./docker-entrypoint.sh"]
    volumes:
      - ./:/app
    ports:
      - "8088:8000"
    environment:
      - POSTGRES_NAME=noboringdate
      - POSTGRES_USER=master
      - POSTGRES_PASSWORD=asqw12ASQW!@
      - DJANGO_SUPERUSER_PASSWORD=12345
    depends_on:
      - db
    networks:
      - djangonetwork
networks:
  djangonetwork:
    driver: bridge
volumes:
  pgdata: