   services:
       nginx:
         image: nginx:1.21.6
         container_name: nginx
         ports:
           - "80:80"
         volumes:
           - ./project/nginx/config.conf:/etc/nginx/conf.d/default.conf
           - appdata:/app
         depends_on:
           - webdjango
         networks:
           - djangonetwork 
       db:
         image: postgres:14
         container_name: db
         restart: always
         volumes:
           - pgdata:/var/lib/postgresql/data
         environment:
           - POSTGRES_DB=postgres
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres
         ports:
           - "5432:5432"
         networks:
           - djangonetwork
       webdjango:
         build: .
         container_name: django
         #  command: python manage.py runserver 0.0.0.0:8000
         entrypoint: ["./docker-entrypoint.sh"]
         volumes:
           - appdata:/app
         ports:
           - "8088:8000"
         environment:
           - POSTGRES_NAME=postgres
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=postgres
           - DJANGO_SUPERUSER_PASSWORD=12345
         depends_on:
           - db
         networks:
           - djangonetwork
   networks:
       djangonetwork:
         driver: bridge
   volumes:
     pgdata:
     appdata: