# Generated by Django 5.1.1 on 2025-01-13 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=50)),
                ('callback', models.CharField(blank=True, max_length=50, null=True)),
                ('row', models.IntegerField(default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Кнопка',
                'verbose_name_plural': 'Кнопки',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('variable', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('=', 'равно'), ('!=', 'не равно'), ('>', 'больше'), ('<', 'меньше')], default='=', max_length=5)),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Условие',
                'verbose_name_plural': 'Условия',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cont', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('cmd', 'cmd'), ('text', 'text'), ('clbck', 'callback')], default='cmd', max_length=10)),
            ],
            options={
                'verbose_name': 'Триггер',
                'verbose_name_plural': 'Триггеры',
            },
        ),
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('inline', 'inline'), ('reply', 'reply')], default='reply', max_length=10)),
                ('buttons', models.ManyToManyField(to='content.button')),
            ],
            options={
                'verbose_name': 'Клавиатура',
                'verbose_name_plural': 'Клавиатуры',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('next_state', models.CharField(blank=True, max_length=100, null=True)),
                ('set_variable', models.CharField(blank=True, max_length=100, null=True)),
                ('set_value', models.CharField(blank=True, max_length=100, null=True)),
                ('delay', models.IntegerField(default=0)),
                ('next_msg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='content.answer')),
                ('conditions', models.ManyToManyField(blank=True, related_name='conditions', to='content.condition')),
                ('kb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.keyboard')),
                ('trigger', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.trigger')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('messages', models.ManyToManyField(blank=True, related_name='group', to='content.answer')),
            ],
            options={
                'verbose_name': 'Группа сообщений',
                'verbose_name_plural': 'Группы сообщений',
            },
        ),
    ]
